import { spawn } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

export async function runWorkerTypes(
  command: 'generate' | 'check',
  configPath = resolve('wrangler.jsonc'),
  outputPath = resolve('worker-configuration.d.ts'),
): Promise<number> {
  const parsed = ts.parseConfigFileTextToJson(
    configPath,
    readFileSync(configPath, 'utf8'),
  );
  if (parsed.error) {
    throw new Error(
      ts.flattenDiagnosticMessageText(parsed.error.messageText, '\n'),
    );
  }
  const config: unknown = parsed.config;
  if (!config || typeof config !== 'object' || Array.isArray(config)) {
    throw new Error('Wrangler configuration must be a JSON object');
  }

  // Keep relative binding paths anchored to the original configuration directory.
  // SvelteKit's generated entrypoint must not affect Env/runtime type generation.
  const typesConfig = { ...config } as Record<string, unknown>;
  delete typesConfig.main;
  const temporaryPath = join(
    dirname(configPath),
    `.worker-types-${randomUUID()}.json`,
  );
  const require = createRequire(import.meta.url);
  const cliPath = resolve(
    dirname(require.resolve('wrangler')),
    '../bin/wrangler.js',
  );
  try {
    writeFileSync(temporaryPath, JSON.stringify(typesConfig), { flag: 'wx' });
    const args = [cliPath, 'types', outputPath, '--config', temporaryPath];
    if (command === 'check') args.push('--check');
    const exitCode = await new Promise<number>((resolveExit, reject) => {
      const child = spawn(process.execPath, args, { stdio: 'inherit' });
      child.once('error', reject);
      child.once('close', code => resolveExit(code ?? 1));
    });
    if (command === 'generate' && exitCode === 0) {
      // Wrangler records CLI arguments, including the temporary config path.
      // Keep that header portable while preserving Wrangler's validation hash.
      const generated = readFileSync(outputPath, 'utf8').replace(
        /^\/\/ Generated by Wrangler.*\(hash: /m,
        '// Generated by Wrangler by running `pnpm gen` (hash: ',
      );
      writeFileSync(outputPath, generated);
    }
    return exitCode;
  } finally {
    rmSync(temporaryPath, { force: true });
  }
}

if (
  process.argv[1] &&
  fileURLToPath(import.meta.url) === resolve(process.argv[1])
) {
  const command = process.argv[2];
  if (command !== 'generate' && command !== 'check') {
    throw new Error('Usage: worker-types.ts <generate|check>');
  }
  process.exitCode = await runWorkerTypes(command);
}
