openapi: 3.0.3
info:
  title: Blog API
  version: 0.2.0
  description: Posts API specification

paths:
  /api/posts:
    get:
      summary: Get list of posts
      operationId: listPosts
      responses:
        200:
          $ref: '#/components/responses/PostList'
        500:
          $ref: '#/components/responses/InternalServerError'

    post:
      summary: Create a post
      operationId: createPost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostInput'
            example:
              $ref: '#/components/examples/PostInputExample'
      responses:
        201:
          $ref: '#/components/responses/SinglePost'
        400:
          $ref: '#/components/responses/BadRequest'
        500:
          $ref: '#/components/responses/InternalServerError'

  /api/posts/{postId}:
    parameters:
      - $ref: '#/components/parameters/PostIdParam'

    get:
      summary: Get post by id
      operationId: getPostById
      responses:
        200:
          $ref: '#/components/responses/SinglePost'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'

    put:
      summary: Update post by id
      operationId: updatePostById
      responses:
        200:
          $ref: '#/components/responses/SinglePost'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'

    delete:
      summary: Delete post by id
      operationId: deletePostById
      responses:
        200:
          $ref: '#/components/responses/SinglePost'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    Post:
      allOf:
        - $ref: '#/components/schemas/PostInput'
        - type: object
          description: Schema for a post
          additionalProperties: false
          required:
            - id
            - createdAt
            - updatedAt
          properties:
            id:
              type: string
              description: The unique identifier for the post
              format: uuid
              example: 4e9344a8-b642-47fb-8e8b-b0f1343f77df
            createdAt:
              type: string
              description: Post creation time
              format: date-time
              example: '2026-01-01T12:00:00Z'
            updatedAt:
              type: string
              description: Post last update time
              format: date-time
              example: '2026-12-31T12:00:00Z'

    PostInput:
      type: object
      description: Schema for post input when creating or updating a post
      additionalProperties: false
      required:
        - title
        - content
      properties:
        title:
          type: string
          description: Post title
          example: My First Post
        content:
          type: string
          description: Post content
          example: This is the content of my first blog

    ApiSuccessResponse:
      type: object
      description: Schema for successful API responses
      additionalProperties: false
      required:
        - success
        - error
      properties:
        success:
          type: boolean
          description: Should always be true for successful responses
          enum: [true]
          example: true
        data:
          oneOf:
            - $ref: '#/components/schemas/Post'
            - type: array
              description: The list of posts returned in the response
              items:
                $ref: '#/components/schemas/Post'
          nullable: true
        error:
          description: Should always be null for successful responses
          enum: [null]
          nullable: true

    ApiErrorResponse:
      type: object
      description: Schema for error API responses
      additionalProperties: false
      required:
        - success
        - data
        - error
      properties:
        success:
          type: boolean
          description: Should always be false for error responses
          enum: [false]
          example: false
        data:
          description: Should always be null for error responses
          enum: [null]
          nullable: true
        error:
          type: object
          description: Error details for the response
          $ref: '#/components/schemas/ApiError'

    ApiError:
      type: object
      additionalProperties: false
      required:
        - code
        - message
        - details
      properties:
        code:
          type: string
          description: A machine-readable error code
          example: POST_NOT_FOUND
        message:
          type: string
          description: A human-readable message describing the error
          example: Post not found
        details:
          oneOf:
            - $ref: '#/components/schemas/InvalidFieldsErrorDetails'
            - $ref: '#/components/schemas/DatabaseErrorDetails'
            - $ref: '#/components/schemas/PostNotFoundErrorDetails'
          nullable: true

    InvalidFieldsErrorDetails:
      type: object
      additionalProperties: false
      required:
        - title
        - content
      properties:
        title:
          type: string
          description: Validation result for the "title" field (e.g. "missing", "invalid type", etc.)
          nullable: true
          example: missing
        content:
          type: string
          description: Validation result for the "content" field (e.g. "missing", "invalid type", etc.)
          nullable: true
          example: null

    DatabaseErrorDetails:
      type: object
      additionalProperties: false
      required:
        - resource
        - hint
      properties:
        resource:
          type: string
          description: The name of the missing database resource
          example: BLOG_DB
        hint:
          type: string
          description: A hint to help resolve the database configuration issue
          example: Please check your wrangler config file or environment variables

    PostNotFoundErrorDetails:
      type: object
      additionalProperties: false
      required:
        - id
      properties:
        id:
          type: string
          format: uuid
          description: The id of the resource that was not found
          example: 4e9344a8-b642-47fb-8e8b-b0f1343f77df

  parameters:
    PostIdParam:
      name: postId
      in: path
      description: The unique identifier of a post
      required: true
      schema:
        type: string
        format: uuid

  responses:
    SinglePost:
      description: The response returned a post
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiSuccessResponse'
          examples:
            created:
              $ref: '#/components/examples/PostCreatedExample'
            retrieved:
              $ref: '#/components/examples/PostResponseExample'
            updated:
              $ref: '#/components/examples/PostResponseExample'
            deleted:
              $ref: '#/components/examples/EmptyResponseExample'

    PostList:
      description: The response returned a list of posts
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiSuccessResponse'
          examples:
            default:
              $ref: '#/components/examples/PostListExample'

    BadRequest:
      description: The request was invalid (e.g. missing required fields, invalid JSON)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiErrorResponse'
          examples:
            missingId:
              $ref: '#/components/examples/MissingIdErrorExample'
            invalidJson:
              $ref: '#/components/examples/InvalidJsonErrorExample'
            invalidFields:
              $ref: '#/components/examples/InvalidFieldErrorExample'

    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiErrorResponse'
          examples:
            default:
              $ref: '#/components/examples/PostNotFoundErrorExample'

    InternalServerError:
      description: An unexpected error occurred on the server
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiErrorResponse'
          examples:
            databaseBindingMissing:
              $ref: '#/components/examples/DatabaseErrorExample'
            serverError:
              $ref: '#/components/examples/ServerErrorExample'

  examples:
    PostInputExample:
      summary: An example of post input for creating or updating a post
      value:
        title: My First Post
        content: This is the content of my first blog

    PostResponseExample:
      summary: An example of a post returned response
      value:
        status: 200
        statusText: OK
        success: true
        data:
          id: 4e9344a8-b642-47fb-8e8b-b0f1343f77df
          title: My First Post
          content: This is the content of my first blog
          createdAt: '2026-01-01T12:00:00Z'
          updatedAt: '2026-12-31T12:00:00Z'
        error: null

    PostCreatedExample:
      summary: An example of a post created response
      value:
        status: 201
        statusText: Created
        success: true
        data:
          id: 4e9344a8-b642-47fb-8e8b-b0f1343f77df
          title: My First Post
          content: This is the content of my first blog
          createdAt: '2026-01-01T12:00:00Z'
          updatedAt: '2026-01-01T12:00:00Z'
        error: null

    EmptyResponseExample:
      summary: An example of an empty response
      value:
        status: 200
        statusText: OK
        success: true
        data: null
        error: null

    PostListExample:
      summary: An example of a list of posts
      value:
        status: 200
        statusText: OK
        success: true
        data:
          - id: 4e9344a8-b642-47fb-8e8b-b0f1343f77df
            title: My First Post
            content: This is the content of my first blog
            createdAt: '2026-01-01T12:00:00Z'
            updatedAt: '2026-12-31T12:00:00Z'
          - id: 5f9344a8-b642-47fb-8e8b-b0f1343f77df
            title: My Second Post
            content: This is the content of my second blog
            createdAt: '2026-02-01T12:00:00Z'
            updatedAt: '2026-12-30T12:00:00Z'
        error: null

    MissingIdErrorExample:
      summary: An example of missing id error response
      value:
        status: 400
        statusText: Bad Request
        success: false
        data: null
        error:
          code: INVALID_REQUEST
          message: Post id is required
          details: null

    InvalidJsonErrorExample:
      summary: An example of invalid JSON error response
      value:
        status: 400
        statusText: Bad Request
        success: false
        data: null
        error:
          code: INVALID_REQUEST
          message: Request body must be a valid JSON object
          details: null

    InvalidFieldErrorExample:
      summary: An example of invalid fields error response
      value:
        status: 400
        statusText: Bad Request
        success: false
        data: null
        error:
          code: INVALID_REQUEST
          message: Request body must be a JSON object with string properties "title" and "content"
          details:
            title: missing
            content: null

    DatabaseErrorExample:
      summary: An example of database binding missing error response
      value:
        status: 500
        statusText: Internal Server Error
        success: false
        data: null
        error:
          code: DATABASE_BINDING_MISSING
          message: The server is not configured correctly
          details:
            resource: BLOG_DB
            hint: Please check your wrangler config file or environment variables

    PostNotFoundErrorExample:
      summary: An example of post not found error response
      value:
        status: 404
        statusText: Not Found
        success: false
        data: null
        error:
          code: POST_NOT_FOUND
          message: Post not found
          details:
            id: 4e9344a8-b642-47fb-8e8b-b0f1343f77df

    ServerErrorExample:
      summary: An example of an unknown server error response
      value:
        status: 500
        statusText: Internal Server Error
        success: false
        data: null
        error:
          code: SERVER_ERROR
          message: An unknown error occurred on the server
          details: null
