/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/posts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get list of posts */
    get: operations['listPosts'];
    put?: never;
    /** Create a post */
    post: operations['createPost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/posts/{postId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The unique identifier of a post */
        postId: components['parameters']['PostIdParam'];
      };
      cookie?: never;
    };
    /** Get post by id */
    get: operations['getPostById'];
    /** Update post by id */
    put: operations['updatePostById'];
    post?: never;
    /** Delete post by id */
    delete: operations['deletePostById'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Post: components['schemas']['PostInput'] & {
      /**
       * Format: uuid
       * @description The unique identifier for the post
       * @example 4e9344a8-b642-47fb-8e8b-b0f1343f77df
       */
      id: string;
      /**
       * Format: date-time
       * @description Post creation time
       * @example 2026-01-01T12:00:00Z
       */
      created_at: string;
      /**
       * Format: date-time
       * @description Post last update time
       * @example 2026-12-31T12:00:00Z
       */
      updated_at: string;
    };
    /** @description Schema for post input when creating or updating a post */
    PostInput: {
      /**
       * @description Post title
       * @example My First Post
       */
      title: string;
      /**
       * @description Post content
       * @example This is the content of my first blog
       */
      content: string;
    };
    /** @description Schema for successful API responses */
    ApiSuccessResponse: {
      /**
       * @description Should always be true for successful responses
       * @example true
       * @enum {boolean}
       */
      success: true;
      data?:
        | (components['schemas']['Post'] | components['schemas']['Post'][])
        | null;
      /**
       * @description Should always be null for successful responses
       * @enum {unknown|null}
       */
      error: null;
    };
    /** @description Schema for error API responses */
    ApiErrorResponse: {
      /**
       * @description Should always be false for error responses
       * @example false
       * @enum {boolean}
       */
      success: false;
      /**
       * @description Should always be null for error responses
       * @enum {unknown|null}
       */
      data: null;
      /** @description Error details for the response */
      error: components['schemas']['ApiError'];
    };
    ApiError: {
      /**
       * @description A machine-readable error code
       * @example POST_NOT_FOUND
       */
      code: string;
      /**
       * @description A human-readable message describing the error
       * @example Post not found
       */
      message: string;
      details:
        | (
            | components['schemas']['InvalidFieldsErrorDetails']
            | components['schemas']['DatabaseErrorDetails']
            | components['schemas']['PostNotFoundErrorDetails']
          )
        | null;
    };
    InvalidFieldsErrorDetails: {
      /**
       * @description Validation result for the "title" field (e.g. "missing", "invalid type", etc.)
       * @example missing
       */
      title: string | null;
      /**
       * @description Validation result for the "content" field (e.g. "missing", "invalid type", etc.)
       * @example null
       */
      content: string | null;
    };
    DatabaseErrorDetails: {
      /**
       * @description The name of the missing database resource
       * @example BLOG_DB
       */
      resource: string;
      /**
       * @description A hint to help resolve the database configuration issue
       * @example Please check your wrangler config file or environment variables
       */
      hint: string;
    };
    PostNotFoundErrorDetails: {
      /**
       * Format: uuid
       * @description The id of the resource that was not found
       * @example 4e9344a8-b642-47fb-8e8b-b0f1343f77df
       */
      id: string;
    };
  };
  responses: {
    /** @description The response returned a post */
    SinglePost: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ApiSuccessResponse'];
      };
    };
    /** @description The response returned a list of posts */
    PostList: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ApiSuccessResponse'];
      };
    };
    /** @description The request was invalid (e.g. missing required fields, invalid JSON) */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ApiErrorResponse'];
      };
    };
    /** @description The specified resource was not found */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ApiErrorResponse'];
      };
    };
    /** @description An unexpected error occurred on the server */
    InternalServerError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ApiErrorResponse'];
      };
    };
  };
  parameters: {
    /** @description The unique identifier of a post */
    PostIdParam: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listPosts: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['PostList'];
      500: components['responses']['InternalServerError'];
    };
  };
  createPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "summary": "An example of post input for creating or updating a post",
         *       "value": {
         *         "title": "My First Post",
         *         "content": "This is the content of my first blog"
         *       }
         *     }
         */
        'application/json': components['schemas']['PostInput'];
      };
    };
    responses: {
      201: components['responses']['SinglePost'];
      400: components['responses']['BadRequest'];
      500: components['responses']['InternalServerError'];
    };
  };
  getPostById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The unique identifier of a post */
        postId: components['parameters']['PostIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['SinglePost'];
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalServerError'];
    };
  };
  updatePostById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The unique identifier of a post */
        postId: components['parameters']['PostIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['SinglePost'];
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalServerError'];
    };
  };
  deletePostById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The unique identifier of a post */
        postId: components['parameters']['PostIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['SinglePost'];
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalServerError'];
    };
  };
}
