/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/posts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a post */
    post: operations['createPost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreatePostInput: {
      title: string;
      content: string;
    };
    Post: {
      /** Format: uuid */
      id: string;
      title: string;
      content: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    ApiError: {
      code: string;
      message: string;
      details: unknown;
    };
    ApiSuccessResponsePost: {
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['Post'];
      error: unknown;
    };
    ApiErrorResponse: {
      /** @enum {boolean} */
      success: false;
      data: unknown;
      error: components['schemas']['ApiError'];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  createPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "title": "My First Post",
         *       "content": "This is the content of my first post."
         *     }
         */
        'application/json': components['schemas']['CreatePostInput'];
      };
    };
    responses: {
      /** @description Post created successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiSuccessResponsePost'];
        };
      };
      /** @description Invalid request body */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "data": null,
           *       "error": {
           *         "code": "INVALID_REQUEST",
           *         "message": "Request body must be a valid JSON object",
           *         "details": null
           *       }
           *     }
           */
          'application/json': components['schemas']['ApiErrorResponse'];
        };
      };
      /** @description Internal server error (bucket not found or unknown server error) */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiErrorResponse'];
        };
      };
    };
  };
}
