/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/posts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List posts */
    get: operations['listPosts'];
    put?: never;
    /** Create a post */
    post: operations['createPost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/posts/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get post by id */
    get: operations['getPostById'];
    /** Update post by id */
    put: operations['updatePostById'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreatePostInput: {
      title: string;
      content: string;
    };
    UpdatePostInput: {
      title: string;
      content: string;
    };
    Post: {
      /** Format: uuid */
      id: string;
      title: string;
      content: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    ApiError: {
      code: string;
      message: string;
      details: components['schemas']['PostNotFoundErrorDetails'] | null;
    };
    PostNotFoundErrorDetails: {
      /** Format: uuid */
      id: string;
    };
    ApiSuccessResponsePost: {
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['Post'];
      /** @enum {unknown|null} */
      error: null;
    };
    ApiSuccessResponsePostList: {
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['Post'][];
      /** @enum {unknown|null} */
      error: null;
    };
    ApiErrorResponse: {
      /** @enum {boolean} */
      success: false;
      /** @enum {unknown|null} */
      data: null;
      error: components['schemas']['ApiError'];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listPosts: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Posts retrieved successfully (sorted by newest first) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiSuccessResponsePostList'];
        };
      };
      /** @description Internal server error (bucket not found or unknown server error) */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiErrorResponse'];
        };
      };
    };
  };
  createPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "title": "My First Post",
         *       "content": "This is the content of my first post."
         *     }
         */
        'application/json': components['schemas']['CreatePostInput'];
      };
    };
    responses: {
      /** @description Post created successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiSuccessResponsePost'];
        };
      };
      /** @description Invalid request body */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "data": null,
           *       "error": {
           *         "code": "INVALID_REQUEST",
           *         "message": "Request body must be a valid JSON object",
           *         "details": null
           *       }
           *     }
           */
          'application/json': components['schemas']['ApiErrorResponse'];
        };
      };
      /** @description Internal server error (bucket not found or unknown server error) */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiErrorResponse'];
        };
      };
    };
  };
  getPostById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Post id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Post retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiSuccessResponsePost'];
        };
      };
      /** @description Invalid request (missing id) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "data": null,
           *       "error": {
           *         "code": "INVALID_REQUEST",
           *         "message": "Post id is required",
           *         "details": null
           *       }
           *     }
           */
          'application/json': components['schemas']['ApiErrorResponse'];
        };
      };
      /** @description Post not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "data": null,
           *       "error": {
           *         "code": "POST_NOT_FOUND",
           *         "message": "Post not found",
           *         "details": {
           *           "id": "4e9344a8-b642-47fb-8e8b-b0f1343f77df"
           *         }
           *       }
           *     }
           */
          'application/json': components['schemas']['ApiErrorResponse'];
        };
      };
      /** @description Internal server error (bucket not found or unknown server error) */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiErrorResponse'];
        };
      };
    };
  };
  updatePostById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Post id */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "title": "Updated title",
         *       "content": "Updated post content."
         *     }
         */
        'application/json': components['schemas']['UpdatePostInput'];
      };
    };
    responses: {
      /** @description Post updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiSuccessResponsePost'];
        };
      };
      /** @description Invalid request body */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "data": null,
           *       "error": {
           *         "code": "INVALID_REQUEST",
           *         "message": "Request body must be a valid JSON object",
           *         "details": null
           *       }
           *     }
           */
          'application/json': components['schemas']['ApiErrorResponse'];
        };
      };
      /** @description Post not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "data": null,
           *       "error": {
           *         "code": "POST_NOT_FOUND",
           *         "message": "Post not found",
           *         "details": {
           *           "id": "4e9344a8-b642-47fb-8e8b-b0f1343f77df"
           *         }
           *       }
           *     }
           */
          'application/json': components['schemas']['ApiErrorResponse'];
        };
      };
      /** @description Internal server error (bucket not found or unknown server error) */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiErrorResponse'];
        };
      };
    };
  };
}
