name: ✅ CI

on:
  push:
    branches: [main]

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || !github.event.pull_request.draft
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Run lint
        run: pnpm lint

  types:
    name: Check types
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || !github.event.pull_request.draft
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Generate worker types
        run: pnpm gen

      - name: Check types
        run: pnpm check

      - name: Generate API types
        run: pnpm gen:api

      - name: Verify generated types are committed
        run: |
          set -e
          FILE_PATH="src/lib/types/schema.d.ts"

          if git diff --quiet -- "$FILE_PATH"; then
            echo "✅ OpenAPI generated type is up-to-date: $FILE_PATH"
            exit 0
          else
            echo "❌ Generated API type is not committed: $FILE_PATH"
            echo "Please run 'pnpm gen:api' and commit the updated file."
            git --no-pager diff -- "$FILE_PATH"
            exit 1
          fi

  test:
    name: Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || !github.event.pull_request.draft
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Install playwright browsers
        run: pnpm exec playwright install

      - name: Run test
        run: pnpm test

  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || !github.event.pull_request.draft
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Run build
        run: pnpm build
