name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY: ${{ secrets.SUPABASE_PUBLISHABLE_DEFAULT_KEY }}

jobs:
  check-lint:
    name: Check lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Run lint
        run: pnpm lint

      - name: Run format-check
        run: pnpm format:check

  check-types:
    name: Check types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Run check-types
        run: pnpm check-types

  verify-db-types:
    name: Verify DB types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Check existence of DB type definition
        run: |
          set -e
          FILE_PATH="src/utils/supabase/database.types.ts"

          git fetch origin main --depth=1
          if git show origin/main:$FILE_PATH > /dev/null 2>&1; then
            echo "✅ Found $FILE_PATH in main branch."
            exit 0
          fi

          if [ -f "$FILE_PATH" ]; then
            echo "✅ Found $FILE_PATH in current PR branch."
            exit 0
          fi

          echo "❌ Not found Supabase DB type definition file!"
          echo "Please commit or generate it using 'pnpm gen-types'."
          exit 1

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Run build for worker
        run: pnpm build:worker

      - name: Run test
        run: pnpm test:run

  merge:
    name: Merge
    needs: [check-lint, check-types, verify-db-types, test]
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Merge pull request
        run: gh pr merge --auto --squash "$PR_URL" --delete-branch
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
